server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always
    info:
      enabled: true
springdoc:
  swagger-ui:

    path: /swagger-ui.html

    enabled: true

    doc-expansion: 'none'
  api-docs:

    path: /v3/api-docs

    enabled: true
  group-configs:
    - group: 'mall-demo'
      packages-to-scan: com.macro.mall.demo.controller
